apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: text-editor-app

resources:
  - servicemonitor.yaml
  - prometheusrule.yaml
  - grafana-dashboard-cm.yaml
  - grafana-instance.yaml
  - grafana-dashboard-resource.yaml
  - prometheus-rules-patch.yaml
